### ISSUE TITLE
Stop needs to be initialized

### ISSUE THREAD

**Issue by soerenab** [MUCDK/ott#2]
**Describe the bug**
`stop` is not initialized when `iter < self.iterations`, see here: https://github.com/MUCDK/ott/blob/draft/neural_base_solver/src/ott/neural/flow_models/genot.py#L291

Error than occurs here: https://github.com/MUCDK/ott/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

**To Reproduce**
Train genot for more than 0 iterations.

**Potential fix**
Initialize stop with False prior to while loop.

**Comment by soerenab** [comment]
Actually, this applies for both `GENOTLin` and `GENOTQuad`.

**Comment by MUCDK** [comment]
Thanks, pushed it.
